# Generated by Django 3.0.8 on 2020-08-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='person',
        ),
    ]
