# Generated by Django 3.0.8 on 2020-08-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_remove_adoptionrequest_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Person'),
        ),
    ]
